# Generated by Django 4.2.1 on 2024-01-09 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{6,20}$', message='"mobile_number" must be in the format "+XXXXXXXX"')]),
        ),
    ]
